import type { CreateFieldPayload } from '../types/template.js';

/**
 * Standard fields that are automatically included in every template.
 * These fields cannot be removed or reordered by admins in the template builder.
 * They always appear at the top of the form before any custom fields.
 */
export const STANDARD_FIELDS: (CreateFieldPayload & { is_standard: true })[] = [
  {
    field_name: 'command',
    field_label: 'Command',
    field_type: 'dropdown',
    is_required: true,
    sort_order: 0,
    options: [
      'NSWG-8',
      'SDVT-1',
      'SDVT-2',
      'SRT-1',
      'SRT-2',
      'LOSGU-8',
      'MSC',
      'IMD',
      'TRADET-8 HI',
      'TRADET-8 CA',
      'TRADET-8 VA',
    ],
    help_text: 'Select the command submitting this request',
    is_standard: true,
  },
  {
    field_name: 'request_type',
    field_label: 'Request Type',
    field_type: 'dropdown',
    is_required: true,
    sort_order: 1,
    options: [
      'Facilities',
      'OCIE',
      'Supplies and Services',
      'Training',
      'Force Generation',
      'Professional Development',
      'Maintenance',
      'MIPR',
    ],
    help_text: 'Select the type of request',
    is_standard: true,
  },
  {
    field_name: 'department_troop',
    field_label: 'Department / Troop',
    field_type: 'text',
    is_required: true,
    sort_order: 2,
    placeholder: 'Enter department or troop',
    help_text: 'Department or troop submitting this request',
    is_standard: true,
  },
  {
    field_name: 'fiscal_year',
    field_label: 'Fiscal Year',
    field_type: 'dropdown',
    is_required: true,
    sort_order: 3,
    options: [
      '2025', '2026', '2027', '2028', '2029', '2030',
      '2031', '2032', '2033', '2034', '2035',
      '2036', '2037', '2038', '2039', '2040',
    ],
    help_text: 'Select the fiscal year for this request',
    is_standard: true,
  },
  {
    field_name: 'fiscal_quarter',
    field_label: 'Fiscal Quarter',
    field_type: 'dropdown',
    is_required: true,
    sort_order: 4,
    options: ['1st', '2nd', '3rd', '4th'],
    help_text: 'Select the fiscal quarter',
    is_standard: true,
  },
  // Primary Requestor
  {
    field_name: 'primary_requestor_name',
    field_label: 'Primary Requestor - Name',
    field_type: 'text',
    is_required: true,
    sort_order: 5,
    placeholder: 'First and last name',
    help_text: 'Full name of the primary requestor',
    is_standard: true,
  },
  {
    field_name: 'primary_requestor_phone',
    field_label: 'Primary Requestor - Phone',
    field_type: 'text',
    is_required: true,
    sort_order: 6,
    placeholder: '(555) 555-5555',
    help_text: 'Phone number for the primary requestor',
    is_standard: true,
  },
  {
    field_name: 'primary_requestor_email',
    field_label: 'Primary Requestor - Email',
    field_type: 'email',
    is_required: true,
    sort_order: 7,
    placeholder: 'email@example.com',
    help_text: 'Email address for the primary requestor',
    is_standard: true,
  },
  {
    field_name: 'primary_requestor_notifications',
    field_label: 'Email notifications on status changes',
    field_type: 'checkbox',
    is_required: false,
    sort_order: 8,
    help_text: 'Receive email push notifications when the request status changes',
    is_standard: true,
  },
  // Secondary Requestor
  {
    field_name: 'secondary_requestor_name',
    field_label: 'Secondary Requestor - Name',
    field_type: 'text',
    is_required: false,
    sort_order: 9,
    placeholder: 'First and last name',
    help_text: 'Full name of the secondary requestor',
    is_standard: true,
  },
  {
    field_name: 'secondary_requestor_phone',
    field_label: 'Secondary Requestor - Phone',
    field_type: 'text',
    is_required: false,
    sort_order: 10,
    placeholder: '(555) 555-5555',
    help_text: 'Phone number for the secondary requestor',
    is_standard: true,
  },
  {
    field_name: 'secondary_requestor_email',
    field_label: 'Secondary Requestor - Email',
    field_type: 'email',
    is_required: false,
    sort_order: 11,
    placeholder: 'email@example.com',
    help_text: 'Email address for the secondary requestor',
    is_standard: true,
  },
  {
    field_name: 'secondary_requestor_notifications',
    field_label: 'Email notifications on status changes',
    field_type: 'checkbox',
    is_required: false,
    sort_order: 12,
    help_text: 'Receive email push notifications when the request status changes',
    is_standard: true,
  },
  {
    field_name: 'priority',
    field_label: 'Priority',
    field_type: 'dropdown',
    is_required: true,
    sort_order: 13,
    options: ['Critical', 'Essential', 'Enhancing'],
    help_text: 'Select the priority level for this request',
    is_standard: true,
  },
  {
    field_name: 'description',
    field_label: 'Description',
    field_type: 'textarea',
    is_required: true,
    sort_order: 14,
    placeholder: 'Provide a detailed description of what you are requesting',
    help_text: 'Describe the item(s) or service(s) you are requesting in detail',
    is_standard: true,
  },
  {
    field_name: 'requested_start_date',
    field_label: 'Requested Start Date / Delivery Date',
    field_type: 'date',
    is_required: true,
    sort_order: 15,
    help_text: 'Select the requested start date or delivery date',
    is_standard: true,
  },
  {
    field_name: 'documents',
    field_label: 'Document Uploads',
    field_type: 'multi_file',
    is_required: false,
    sort_order: 16,
    help_text: 'Upload up to 10 supporting documents (PDF, images, Word, Excel, PowerPoint — max 10MB each)',
    is_standard: true,
  },
];

/** Number of standard fields - custom fields should start their sort_order after this */
export const STANDARD_FIELDS_COUNT = STANDARD_FIELDS.length;
